LIVETEST_OPERATION_ID = "pplt"
PODPING_OPERATION_ID = "pp"
STARTUP_OPERATION_ID = "_startup"

EXIT_CODE_UNKNOWN = 10
EXIT_CODE_INVALID_POSTING_KEY = 20
EXIT_CODE_HIVE_API_ERROR = 30
EXIT_CODE_INVALID_ACCOUNT = 40
PODPING_SETTINGS_KEY = "podping-settings"

# Operation JSON must be less than or equal to 8192 bytes.
HIVE_CUSTOM_OP_DATA_MAX_LENGTH = 8192
