LIVETEST_OPERATION_ID = "podping-livetest"
PODPING_OPERATION_ID = "podping"
STARTUP_OPERATION_ID = "podping-startup"

STARTUP_FAILED_UNKNOWN_EXIT_CODE = 10
STARTUP_FAILED_INVALID_POSTING_KEY_EXIT_CODE = 20
STARTUP_FAILED_HIVE_API_ERROR_EXIT_CODE = 30
PODPING_SETTINGS_KEY = "podping-settings"
