LIVETEST_OPERATION_ID = "pplt"
PODPING_OPERATION_ID = "pp"
STARTUP_OPERATION_ID = "_startup"

STARTUP_FAILED_UNKNOWN_EXIT_CODE = 10
STARTUP_FAILED_INVALID_POSTING_KEY_EXIT_CODE = 20
STARTUP_FAILED_HIVE_API_ERROR_EXIT_CODE = 30
STARTUP_FAILED_INVALID_ACCOUNT = 40
PODPING_SETTINGS_KEY = "podping-settings"

# Operation JSON must be less than or equal to 8192 bytes.
HIVE_CUSTOM_OP_DATA_MAX_LENGTH = 8192
