name: PyPi publish

on:
  release:
    types: [ published ]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: agates/poetry-publish@v1.10-beta.0
        with:
          ignore_dev_requirements: "yes"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          extra_build_dependency_packages: "capnproto libzmq3-dev"